"""add rating to product

Revision ID: 16968410d301
Revises: a3e6a36cef98
Create Date: 2025-05-20 01:57:35.203346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16968410d301'
down_revision = 'a3e6a36cef98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
